from tkinter import*
window=Tk()
window.title("my program")
ani=Label(window,text="Mai Hu Aniket",fg='red')
ani.place(x=60,y=40)
ab=Button(window,text="press for yes",fg='blue')
ab.place(x=60, y=80)
cat=Entry(window,text="enter ur name",bd=20,bg='red')
cat.place(x=60,y=120)
a=IntVar()
b=IntVar()
c1=Checkbutton(window,text="aniket",fg='red',variable=a)
c2=Checkbutton(window,text="Shivam",variable=b)
c1.place(x=60,y=180)
c2.place(x=180,y=180)
window.mainloop()
